version: 2

project_name: graph-go

builds:
  - main: ./cmd/app
    binary: graph-go
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.Version={{ .Version }} -X main.Commit={{ .Commit }} -X main.BuildDate={{ .Date }}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
  groups:
    - title: Features
      regexp: "^.*feat.*$"
      order: 0
    - title: Bug Fixes
      regexp: "^.*fix.*$"
      order: 1
    - title: Other
      order: 999
